import Head from 'next/head'
import { useState } from 'react';
import Playlist from '../components/Playlist'
import Title from '../components/Title'

//fetching the data
export const getStaticProps = async () => {
  const res = await fetch(
    "https://unsa-unofficial-spotify-api.p.rapidapi.com/search?query=a&count=50&type=tracks",
    {
      method: "GET",
      headers: {
        "x-rapidapi-host": process.env.RAPIDAPI_HOST,
        "x-rapidapi-key": process.env.RAPIDAPI_KEY,
      },
    }
  );
  const data = await res.json();

  if (!data) {
     return {
       notFound: true,
     }
  }

  return {
    props: {data}
  }
}

export default function Home({ data }) {

  const [tracks, setTracks] = useState(data.Results)

  return (
    <div>
      <Head>
        <title>Tracks Book App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='box-border'>
        <Title setTracks={ setTracks } />
        <Playlist tracks={ tracks } />
      </main>
    </div>
  )
}
